logging:
  level: INFO
  loggers:
    honstain: DEBUG
  appenders:
#    - type: console
#      threshold: DEBUG
#      layout:
#        type: json
#        flattenMdc: true
      - type: console
        threshold: DEBUG
        layout:
          type: json
          flattenMdc: true

# Setup initial configuration following Dropwizard docs - dropped HTTPS and certs
# https://www.dropwizard.io/en/latest/manual/configuration.html#default
server:
  minThreads: 10
  maxThreads: 100 # Setting this super low to help me explore the system under resource constraints
  adminMinThreads: 1
  adminMaxThreads: 4
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 7070
  adminConnectors:
    - type: http
      port: 7071
  requestLog:
    appenders:
      - type: file
        threshold: ALL
        layout:
          type: access-json
          timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
          prettyPrint: false
          appendLineSeparator: true
          includes: [timestamp, remoteAddress, remoteUser, protocol, method, requestUri, statusCode, requestTime, contentLength, userAgent]
          requestHeaders:
            - ProvenanceID
#          responseHeaders:
#            - X-Request-Id
#          requestAttributes:
#            - SomeAttributeName
          customFieldNames:
            timestamp: "@timestamp"
          additionalFields:
            service-name: "product-service"
        logFormat:  "%h %l %u [%date{ISO8601}] %I '%r' %s %b '%i{Referer}' '%i{User-Agent}' %D"
        #logFormat:  "%h %l %u [%t] '%r' %s %b '%i{Referer}' '%i{User-Agent}' %D"
        #logFormat: '%h [%date{ISO8601}] "%r" %s %b %D [%i{User-Agent}]'
        currentLogFilename: ./logs/PRODUCT_request.log
        archivedLogFilenamePattern: ./logs/PRODUCT_request-%d.log.gz
        archivedFileCount: 5

metrics:
  reporters:
    - type: graphite
      host: localhost
      port: 2003
      prefix: ProductService.1
      transport: tcp
      durationUnit: milliseconds
      rateUnit: seconds
      frequency: 5 second

producer:
  type: basic
  bootstrapServers:
    - 127.0.0.1:29092
#    - 127.0.0.1:9093
#    - 127.0.0.1:9094
  name: producerNameToBeUsedInMetrics
  keySerializer:
    type: string
  valueSerializer:
    type: string
  acks: all
  retries: 0
  maxInFlightRequestsPerConnection: 1
  maxPollBlockTime: 10s
#  security:
#    securityProtocol: sasl_ssl
#    sslProtocol: TLSv1.2
#    saslMechanism: PLAIN
#    saslJaas: "org.apache.kafka.comm