logging:
  level: INFO
  loggers:
    honstain: DEBUG
#  appenders:
#    - type: console
#      threshold: DEBUG
#      layout:
#        type: json
#        flattenMdc: true

# Setup initial configuration following Dropwizard docs - dropped HTTPS and certs
# https://www.dropwizard.io/en/latest/manual/configuration.html#default
server:
  minThreads: 4
  maxThreads: 4 # Setting this super low to help me explore the system under resource constraints
  adminMinThreads: 1
  adminMaxThreads: 4
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 7070
  adminConnectors:
    - type: http
      port: 7071
  requestLog:
    appenders:
      - type: console
        threshold: ALL
        layout:
          type: access-json
          timestampFormat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
          prettyPrint: false
          appendLineSeparator: true
          includes: [timestamp, remoteAddress, remoteUser, protocol, method, requestUri, statusCode, requestTime, contentLength, userAgent]
          requestHeaders:
            - ProvenanceID
#          responseHeaders:
#            - X-Request-Id
#          requestAttributes:
#            - SomeAttributeName
          customFieldNames:
            timestamp: "@timestamp"
          additionalFields:
            service-name: "product-service"