{
 "title": "Dropwziard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jetty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "ProductService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.utilization"
    }
   ]
  },
  {
   "title": "Utilization Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "ProductService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.utilization-max"
    }
   ]
  },
  {
   "title": "Job Queue Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "ProductService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.jobs-queue-utilization"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "ProductService.*.org.eclipse.jetty.util.thread.QueuedThreadPool.dw.jobs"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "MustableServletContextHandler request count rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "derivative(ProductService.*.io.dropwizard.jetty.MutableServletContextHandler.requests.count)"
    },
    {
     "target": "derivative(ProductService.*.io.dropwizard.jetty.MutableServletContextHandler.5xx-responses.count)"
    }
   ]
  },
  {
   "title": "ProductResource Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "derivative(ProductService.*.honstain.ProduceResource.*.total.count)"
    }
   ]
  },
  {
   "title": "ProductResource Total P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "ProductService.*.honstain.ProduceResource.*.total.p99"
    }
   ]
  },
  {
   "title": "HttoConnectionFactory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "HttpConnectionFactory Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "target": "derivative(ProductService.*.org.eclipse.jetty.server.HttpConnectionFactory.7070.connections.count)"
    }
   ]
  },
  {
   "title": "HttpConnectionFactory Connection Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "ProductService.*.org.eclipse.jetty.server.HttpConnectionFactory.7070.connections.mean"
    }
   ]
  }
 ]
}